[package]
name = "rispy"
version = "0.0.3"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/takashiidobe/rispy"
description = "A Lisp in Rust"
documentation = "https://docs.rs/rispy"
